### ISSUE TITLE
Signature verification fails for larger files

### ISSUE THREAD

**Issue by ejoerns** [jluebbe/rauc#7]
For larger files, we get a malloc error and verification failes. Tested here with a ~200MB bundle.

** Message: Verifying bundle... 
3061376208:error:07069041:memory buffer routines:BUF_MEM_grow_clean:malloc failure:buffer.c:159:

** (rauc:406): WARNING **: signature invalid (squashfs size: 201342976)

**Comment by jluebbe** [comment]
This was fixed by pull-request #8 (bundle.c: set size return parameter earlier in check_bundle).
